name: automkdocs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Auto MkDocs
      run: |
        cd ${{ github.workspace }}/docs &&\
        pip install mkdocs &&\
        mkdocs build .
